### ISSUE TITLE
Amazon RDS: Permission denied for database rdsadmin

### ISSUE THREAD

**Issue by maedox** [aouyar/PyMunin#48]
When connecting to an Amazon RDS instance I get the following error. Using exclude_db doesn't help, but I guess it only excludes from detailed graphs.

Is there a way around this? I can't change any permissions on the rdsadmin database because Amazon has locked it down.

```python
2015/02/17-13:03:26 [29798] Error output from pgstats_tixdb:
2015/02/17-13:03:26 [29798]     ERROR: ProgrammingError('permission denied for database rdsadmin\n',)
2015/02/17-13:03:26 [29798]     Traceback (most recent call last):
2015/02/17-13:03:26 [29798]       File "/etc/munin/plugins/pgstats_tixdb", line 9, in <module>
2015/02/17-13:03:26 [29798]         load_entry_point('PyMunin==0.9.27', 'console_scripts', 'pymunin-pgstats')()
2015/02/17-13:03:26 [29798]       File "/usr/local/lib/python2.7/dist-packages/pymunin/plugins/pgstats.py", line 507, in main
2015/02/17-13:03:26 [29798]         sys.exit(muninMain(MuninPgPlugin))
2015/02/17-13:03:26 [29798]       File "/usr/local/lib/python2.7/dist-packages/pymunin/__init__.py", line 958, in muninMain
2015/02/17-13:03:26 [29798]         ret = plugin.run()
2015/02/17-13:03:26 [29798]       File "/usr/local/lib/python2.7/dist-packages/pymunin/__init__.py", line 775, in run
2015/02/17-13:03:26 [29798]         ret = self.fetch()
2015/02/17-13:03:26 [29798]       File "/usr/local/lib/python2.7/dist-packages/pymunin/__init__.py", line 750, in fetch
2015/02/17-13:03:26 [29798]         self.retrieveVals()
2015/02/17-13:03:26 [29798]       File "/usr/local/lib/python2.7/dist-packages/pymunin/plugins/pgstats.py", line 391, in retrieveVals
2015/02/17-13:03:26 [29798]         stats = self._dbconn.getDatabaseStats()
2015/02/17-13:03:26 [29798]       File "/usr/local/lib/python2.7/dist-packages/pysysinfo/postgresql.py", line 219, in getDatabaseStats
2015/02/17-13:03:26 [29798]         % ",".join(headers[:-1]))
2015/02/17-13:03:26 [29798]     psycopg2.ProgrammingError: permission denied for database rdsadmin
2015/02/17-13:03:26 [29798] Service 'pgstats_tixdb' exited with status 1/0.
```

**Comment by maedox** [comment]
For the record, adding env.include_db doesn't help either.

**Comment by notpeter** [comment]
Despite being documented, I'm pretty sure include_db and exclude_db are in fact not implemented in code.
